openapi: 3.0.0
info:
  title: test
  version: '1.0'
  description: |-
    Description goes here

    ```yaml http
    {
      "method": "post",
      "url": "https://example.com/v1/numbers/{number}",
      "headers": "\"content-type\": \"application/json;charset=UTF-8\"",
      "body": "{\"foo\":true}"
    }
    ```
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
